In [1]:
import pandas as pd
import os

In [2]:
caminho_arquivos ="../04 Seleção e Filtragem de Dados/dados/TargetSales/"

customers = pd.read_csv(f"{caminho_arquivos}customers.csv",dtype={"customer_zip_code_prefix": "str"} )
geolocations = pd.read_csv(f"{caminho_arquivos}geolocation.csv",dtype={"geolocation_zip_code_prefix": "str"})
order_items = pd.read_csv(f"{caminho_arquivos}order_items.csv",parse_dates=["shipping_limit_date"])
orders = pd.read_csv(f"{caminho_arquivos}orders.csv", parse_dates=["order_purchase_timestamp","order_approved_at","order_delivered_carrier_date","order_delivered_customer_date","order_estimated_delivery_date"])
payments = pd.read_csv(f"{caminho_arquivos}payments.csv")
products = pd.read_csv(f"{caminho_arquivos}products.csv")
sellers = pd.read_csv(f"{caminho_arquivos}sellers.csv", dtype={"sellers_zip_code_prefix": "str"})

In [3]:
os.getcwd()

'/Users/eduardowatanabe/CursoPythonAD/Treinando-Analise-python/05 Limpeza e preparação dos dados'

In [21]:
os.chdir("..")
print(os.getcwd())
print(os.listdir())

/Users/eduardowatanabe/CursoPythonAD/Treinando-Analise-python
['.DS_Store', '03 Importando e armazenando dados', 'README.md', '05 Limpeza e preparação dos dados', '04 Seleção e Filtragem de Dados', '.gitattributes', '.git', '01 dados_exemplo.csv', 'venv2', '02 estruturas pandas.ipynb']

In [22]:
# mudar para um diretorio especifico 

os.chdir('04 Seleção e Filtragem de Dados')
print(os.getcwd())
print(os.listdir())

/Users/eduardowatanabe/CursoPythonAD/Treinando-Analise-python/04 Seleção e Filtragem de Dados
['.DS_Store', '04 selecao e filtragem de dados.ipynb', 'dados', 'arquivos']

In [23]:
# mudar para um diretorio especifico 

os.chdir('dados/TargetSales')
print(os.getcwd())
print(os.listdir())

/Users/eduardowatanabe/CursoPythonAD/Treinando-Analise-python/04 Seleção e Filtragem de Dados/dados/TargetSales
['customers.csv', 'products.csv', 'orders.csv', 'geolocation.csv', 'payments.csv', 'sellers.csv', 'order_items.csv']

In [5]:
# sabendo quais valores ha dentro da coluna 
orders ['order_status']. unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [6]:
#filtrando o dataframe orders com status 'delivered', ' shipped'
orders_shipped_delivered = orders[orders['order_status'].isin(['delivered', 'shipped' ])]
# valindando a informacao 
orders_shipped_delivered[ 'order_status'].unique()

array(['delivered', 'shipped'], dtype=object)

In [9]:
pd.pivot_table(
    orders_shipped_delivered,
    index="order_status",
    values="order_id",
    aggfunc="count"
)

              order_id
order_status
delivered        96478
shipped           1107

In [11]:
delivered_status_list= []

for index, row in orders_shipped_delivered.iterrows():
    if row["order_delivered_customer_date"]> row["order_estimated_delivery_date"]:
        delivered_status_list.append("atrasado")
    elif row["order_estimated_delivery_date"] >=row["order_delivered_customer_date"]:
        delivered_status_list.append("no tempo")
    else:
        delivered_status_list.append("shipped")

orders_shipped_delivered["delivery_status"]= delivered_status_list

orders_shipped_delivered.head(4)

/var/folders/zz/hvwkhzpn12nfsccrl5hmgmt80000gn/T/ipykernel_57843/4262314000.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_shipped_delivered["delivery_status"]= delivered_status_list

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,no tempo
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,no tempo
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,no tempo
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,no tempo

In [13]:
print(len(delivered_status_list), len(orders_shipped_delivered))

97585 97585

In [10]:
orders_shipped_delivered.head(2)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13