In [ ]:
import pandas as pd

In [65]:
caminho_arquivos ="dados/TargetSales/"

In [68]:
customers = pd.read_csv(f"{caminho_arquivos}customers.csv",dtype={"customer_zip_code_prefix": "str"} )
geolocations = pd.read_csv(f"{caminho_arquivos}geolocation.csv",dtype={"geolocation_zip_code_prefix": "str"})
order_items = pd.read_csv(f"{caminho_arquivos}order_items.csv",parse_dates=["shipping_limit_date"])
orders = pd.read_csv(f"{caminho_arquivos}orders.csv", parse_dates=["order_purchase_timestamp","order_approved_at","order_delivered_carrier_date","order_delivered_customer_date","order_estimated_delivery_date"])
payments = pd.read_csv(f"{caminho_arquivos}payments.csv")
products = pd.read_csv(f"{caminho_arquivos}products.csv")
sellers = pd.read_csv(f"{caminho_arquivos}sellers.csv", dtype={"sellers_zip_code_prefix": "str"})

In [69]:
orders = pd.read_csv(f"{caminho_arquivos}orders.csv", parse_dates=["order_purchase_timestamp","order_approved_at","order_delivered_carrier_date","order_delivered_customer_date","order_estimated_delivery_date"])

In [20]:
products["product_photos_qty"] = products["product_photos_qty"].fillna(0)
products["product_photos_qty"] = products["product_photos_qty"].astype(int)
products.dtypes

product_id                     object
product category               object
product_name_length           float64
product_description_length    float64
product_photos_qty              int64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [24]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [ ]:
culunas_escolhidas= ['order_id', 'customer_id', 'order_status','order_delivered_customer_date']
orders[culunas_escolhidas].head(2)

,order_id,customer_id,order_status,order_delivered_customer_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-10 21:25:13
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-08-07 15:27:45

In [ ]:
# transformar o dataframe apenas com colunas selecionadas
orders=orders[culunas_escolhidas]
orders.head(2)

,order_id,customer_id,order_status,order_delivered_customer_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-10 21:25:13
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-08-07 15:27:45

In [31]:
orders_atuais = ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date']
orders_novas = ['id_da_ordem', 'id_do_cliente', 'status_da_orde,', 'data_compra',
       'data_aprovado', 'data_transportadora',
       'data_entrega', 'data_prevista']
orders.columns = orders_novas
orders.head(2)

,id_da_ordem,id_do_cliente,"status_da_orde,",data_compra,data_aprovado,data_transportadora,data_entrega,data_prevista
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13

In [33]:
orders = orders.rename(columns={ 'data_transportadora': 'data_entregue_transpoprtadora' })

orders.head(2)

,id_da_ordem,id_do_cliente,"status_da_orde,",data_compra,data_aprovado,data_entregue_transpoprtadora,data_entrega,data_prevista
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13

In [5]:
products

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,sport leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,babies,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,Furniture Decoration,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,Construction Tools Illumination,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed table bath,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,computer accessories,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,bed table bath,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [11]:
products.at[1,"product category"]

'Art'

In [12]:
products.iat[1,1]

'Art'

In [26]:
products.loc[products["product category"]=="Art"].head(5)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
129,cbaff83e2c00a2b731d27276bbf52082,Art,59.0,1431.0,6.0,7900.0,70.0,15.0,70.0
233,aedb7e30007f6051c5b3f97156b0848a,Art,32.0,195.0,1.0,150.0,25.0,2.0,19.0
1600,b0694770dbbfebe2d48cd288cfce2f85,Art,35.0,1190.0,1.0,15400.0,100.0,4.0,60.0
1957,056d07eb7d9c446e3780a3a7f102190d,Art,48.0,135.0,1.0,500.0,50.0,6.0,20.0

In [18]:
products.iloc[:5,:5]

,product_id,product category,product_name_length,product_description_length,product_photos_qty
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0
2,96bd76ec8810374ed1b65e291975717f,sport leisure,46.0,250.0,1.0
3,cef67bcfe19066a932b7673e239eb23d,babies,27.0,261.0,1.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0

In [20]:
products[products["product_weight_g"]>=10000].head(2)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
6,732bd381ad09e530fe0a5f457d81becb,Cool Stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
44,7a8dac4aaa16bc642e4df33adcf03303,Cool Stuff,38.0,1701.0,2.0,11750.0,18.0,40.0,79.0

In [25]:
products[products["product category"] == "babies"].head(5)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
3,cef67bcfe19066a932b7673e239eb23d,babies,27.0,261.0,1.0,371.0,26.0,4.0,26.0
11,03b63c5fc16691530586ae020c345514,babies,49.0,728.0,4.0,7150.0,50.0,19.0,45.0
23,8b41fbc2b984a12030090112324d1bc4,babies,55.0,1627.0,1.0,500.0,20.0,13.0,13.0
35,5370b82a213393979691c98074265584,babies,52.0,708.0,9.0,7950.0,33.0,30.0,44.0
43,b864b103180d5a6a3f830e67f93e8735,babies,47.0,980.0,4.0,600.0,70.0,11.0,11.0

In [26]:
# and => &
# or => |
products[(products["product category"]=="babies") & (products["product_weight_g"]>= 10000)]

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
217,6e9c52b407fea24064f7ab2b144fbf8c,babies,56.0,1395.0,7.0,13575.0,71.0,81.0,44.0
474,b5d214651360e2d58e13b48ae69c6199,babies,46.0,1654.0,6.0,10400.0,100.0,23.0,27.0
643,f3979f97b4913d696bbe9c7c425c5e4e,babies,36.0,654.0,3.0,18667.0,88.0,28.0,67.0
849,375478581c97832540b9209722a32058,babies,60.0,566.0,1.0,17600.0,65.0,36.0,45.0
977,0eb41884a8773e019708fb8409fd8347,babies,41.0,1064.0,1.0,21467.0,76.0,57.0,51.0
...,...,...,...,...,...,...,...,...,...
31693,f11c4213fbb2d511dc25037a3c31117b,babies,56.0,487.0,1.0,14000.0,62.0,47.0,32.0
31844,90f86af7210af277623dc9d9b7efd909,babies,42.0,829.0,5.0,12100.0,44.0,44.0,53.0
31865,ff7885ae23429394b64526e957ec809d,babies,35.0,1138.0,4.0,11825.0,64.0,25.0,40.0
32500,e80d316020758033fb0247e553f8a640,babies,35.0,547.0,2.0,12000.0,65.0,97.0,18.0
32823,cba32576375902a87170bedaed045b71,babies,58.0,1882.0,4.0,11467.0,35.0,57.0,52.0

In [29]:
# or => |
products[(products["product category"]== "Furniture Decoration") | (products["product category"]=="Construction Tools Illumination")].head(10)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
7,2548af3e6e77a690cf3eb6368e9ab61e,Furniture Decoration,56.0,184.0,2.0,900.0,40.0,8.0,40.0
13,7bb6f29c2be57716194f96496660c7c2,Furniture Decoration,51.0,2083.0,2.0,600.0,68.0,11.0,13.0
18,a0736b92e52f6cead290e30b578413b6,Furniture Decoration,56.0,296.0,2.0,1700.0,100.0,7.0,15.0
20,1c1890ba1779090cd54008a3c3302921,Furniture Decoration,27.0,158.0,4.0,2550.0,29.0,24.0,45.0
24,d03bd02af9fff4b98f1c972315e5e9ef,Furniture Decoration,56.0,209.0,1.0,1800.0,40.0,10.0,30.0
32,20e37962088a4061d3578def47a8648b,Furniture Decoration,60.0,208.0,1.0,800.0,40.0,10.0,34.0
39,680874c570dad71c0a2844cfbf417054,Furniture Decoration,47.0,502.0,1.0,600.0,25.0,25.0,25.0
40,8b3a9476f74f5297f7ff0ec6d95fe1ea,Furniture Decoration,63.0,254.0,2.0,2050.0,49.0,13.0,41.0
47,bbf920aa6ac72007a726e6f419156f8f,Furniture Decoration,42.0,303.0,2.0,1300.0,25.0,16.0,25.0
48,c3b7e4d83e530c27a8e6368296aece48,Furniture Decoration,60.0,1972.0,2.0,850.0,69.0,11.0,11.0

In [32]:
products [(products ['product_weight_g']>= 1000) & (products ['product_weight_g']<= 3000)]

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
10,14aa47b7fe5c25522b47b4b29c98dcb9,bed table bath,54.0,630.0,1.0,1100.0,16.0,10.0,16.0
18,a0736b92e52f6cead290e30b578413b6,Furniture Decoration,56.0,296.0,2.0,1700.0,100.0,7.0,15.0
20,1c1890ba1779090cd54008a3c3302921,Furniture Decoration,27.0,158.0,4.0,2550.0,29.0,24.0,45.0
24,d03bd02af9fff4b98f1c972315e5e9ef,Furniture Decoration,56.0,209.0,1.0,1800.0,40.0,10.0,30.0
...,...,...,...,...,...,...,...,...,...
32938,59dae5028ffa06d8f0151bf1fa97b7e6,computer accessories,38.0,433.0,1.0,1100.0,36.0,15.0,25.0
32942,16280ca280a86fee2ba3c928ed04439f,Furniture Decoration,64.0,236.0,11.0,2200.0,31.0,11.0,26.0
32947,bf4538d88321d0fd4412a93c974510e6,Construction Tools Illumination,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed table bath,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32950,106392145fca363410d287a815be6de4,bed table bath,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [33]:
# valindando criterio 
# products [(products ['product_weight_g']>= 1000) & (products ['product_weight_g']<= 3000)]['product_weight_g'].max()
products [(products ['product_weight_g']>= 1000) & (products ['product_weight_g']<= 3000)]['product_weight_g'].min()

np.float64(1000.0)

In [24]:
#between
products [products[ 'product_weight_g'].between (1000,3000)].head(5)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
10,14aa47b7fe5c25522b47b4b29c98dcb9,bed table bath,54.0,630.0,1.0,1100.0,16.0,10.0,16.0
18,a0736b92e52f6cead290e30b578413b6,Furniture Decoration,56.0,296.0,2.0,1700.0,100.0,7.0,15.0
20,1c1890ba1779090cd54008a3c3302921,Furniture Decoration,27.0,158.0,4.0,2550.0,29.0,24.0,45.0
24,d03bd02af9fff4b98f1c972315e5e9ef,Furniture Decoration,56.0,209.0,1.0,1800.0,40.0,10.0,30.0

In [23]:
# isin
# validando o filtro
# products[products["product category"].isin(["perfumery","Art","babies"])]["product category"].unique()
products[products["product category"].isin(["perfumery","Art","babies"])].head(5)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
3,cef67bcfe19066a932b7673e239eb23d,babies,27.0,261.0,1.0,371.0,26.0,4.0,26.0
11,03b63c5fc16691530586ae020c345514,babies,49.0,728.0,4.0,7150.0,50.0,19.0,45.0
16,6a2fb4dd53d2cdb88e0432f1284a004c,perfumery,39.0,346.0,2.0,400.0,27.0,5.0,20.0

In [21]:
products[products["product category"].isna()].head(5)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

In [20]:
# isnull
products[products["product category"].isnull()].head(5)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

In [28]:
#contains
products [products[ 'product category'].str.contains('sport', na=False)].head(5)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
2,96bd76ec8810374ed1b65e291975717f,sport leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
15,3bb7f144022e6732727d8d838a7b13b3,sport leisure,22.0,3021.0,1.0,800.0,16.0,2.0,11.0
29,051b9ff13dd55c0a6655a15ff296f80d,sport leisure,50.0,529.0,2.0,3600.0,62.0,23.0,23.0
34,ce5b91848b91118daffb3af53b747475,sport leisure,50.0,699.0,4.0,1388.0,34.0,9.0,31.0
50,5eaa343860dc445b3fd43d1b682809fd,sport leisure,53.0,3218.0,5.0,4800.0,60.0,30.0,15.0

In [29]:
#validando categorias com sport
products [products[ 'product category'].str.contains('sport', na=False)]['product category']. unique ()

array(['sport leisure'], dtype=object)

In [30]:
#contains mais de um texto ou critério
products [products[ 'product category'].str.contains('sport|ware', na=False)] .head()

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
2,96bd76ec8810374ed1b65e291975717f,sport leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0
15,3bb7f144022e6732727d8d838a7b13b3,sport leisure,22.0,3021.0,1.0,800.0,16.0,2.0,11.0
25,8ba4f2a4ae695d26e5626c1bf710975e,housewares,52.0,968.0,1.0,900.0,50.0,5.0,50.0
29,051b9ff13dd55c0a6655a15ff296f80d,sport leisure,50.0,529.0,2.0,3600.0,62.0,23.0,23.0

In [ ]:
# NOT (~)
products [~(products ['product_weight_g'] >=10000)].head()

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,sport leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,babies,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
#dois critérios de not (~)
products [(products ['product_weight_g']>=10000) & ~(products["product category"]== "babies")].head()

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
6,732bd381ad09e530fe0a5f457d81becb,Cool Stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
44,7a8dac4aaa16bc642e4df33adcf03303,Cool Stuff,38.0,1701.0,2.0,11750.0,18.0,40.0,79.0
46,5f504b3a1c75b73d6151be81eb05bdc9,Cool Stuff,38.0,1176.0,3.0,15350.0,47.0,40.0,47.0
68,1e5428c428e0f783acd6e3d94ba4ee2a,PCs,55.0,1067.0,1.0,12000.0,27.0,50.0,53.0
70,d0389f20b3d11de54e1e4561df147683,Casa Construcao,55.0,1441.0,1.0,10000.0,60.0,25.0,25.0

In [ ]:
# merge (join)
pd.merge(
orders, customers, how='left', on="customer_id").head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,03149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,09195,santo andre,SP

In [38]:
# Merge  com campos com nome diferente
pd.merge(
orders, customers, how='left', left_on="customer_id", right_on="customer_id").head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,03149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,09195,santo andre,SP

In [39]:
#filtrando os campos
pd.merge(
orders,
customers[[ 'customer_id', 'customer_city', 'customer_state']], how='left', left_on="customer_id", right_on="customer_id"
).head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,santo andre,SP

In [40]:
#filtrando os campos
pd.merge(
orders [['customer_id', 'order_status']], 
customers[[ 'customer_id', 'customer_city', 'customer_state']], 
how='left', left_on="customer_id", right_on="customer_id").head()

,customer_id,order_status,customer_city,customer_state
0,9ef432eb6251297304e76186b10a928d,delivered,sao paulo,SP
1,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,barreiras,BA
2,41ce2a54c0b03bf3443c3d931a367089,delivered,vianopolis,GO
3,f88197465ea7920adcdbec7375364d82,delivered,sao goncalo do amarante,RN
4,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,santo andre,SP

In [22]:
products.head(5)

,product_id,product category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,sport leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,babies,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [52]:
products[(products["product category"]=="babies")]
qnti_babies = len(products[(products["product category"]=="babies")])
print(qnti_babies)

919

In [57]:
# Quantos produtos cadastrados tem o peso entre 10 e 13kg?
qnt_total = len(products [products[ 'product_weight_g'].between (10000,13000)])
print(qnt_total)

642

In [48]:
products["product category"].unique()

array(['perfumery', 'Art', 'sport leisure', 'babies', 'housewares',
       'musical instruments', 'Cool Stuff', 'Furniture Decoration',
       'home appliances', 'toys', 'bed table bath',
       'CONSTRUCTION SECURITY TOOLS', 'computer accessories',
       'HEALTH BEAUTY', 'Bags Accessories', 'Garden tools',
       'Furniture office', 'automotive', 'electronics',
       'Fashion Calcados', 'telephony', 'stationary store',
       'Fashion Bags and Accessories', 'PCs', 'Casa Construcao',
       'Watches present', 'Construction Tools Construction', 'pet Shop',
       'electrostile', 'Agro Industria e Comercio', nan, 'Room Furniture',
       'SIGNALIZATION AND SAFETY', 'climatization', 'Games consoles',
       'General Interest Books', 'Construction Tools Tools',
       'Fashion Underwear and Beach Fashion', "Fashion Men's Clothing",
       'Furniture Kitchen Service Area Dinner and Garden',
       'Industry Commerce and Business', 'fixed telephony',
       'Construction Tools Illumination', 'technical books',
       'ELECTRICES 2', 'party articles', 'drinks', 'Market Place',
       'La Cuisine', 'Construction Tools Garden',
       "Fashion Women's Clothing", 'House comfort', 'audio',
       'Drink foods', 'song', 'foods', 'IMAGE IMPORT TABLETS',
       'Imported books', 'HOUSE PASTALS OVEN AND CAFE', 'Fashion Sport',
       'Christmas articles', "Fashion Children's Clothing",
       'Blu Ray DVDs', 'Arts and Crafts', 'PC Gamer', 'Furniture',
       'cine photo', 'Hygiene diapers', 'flowers', 'House Comfort 2',
       'Kitchen portable and food coach', 'insurance and services',
       'CITTE AND UPHACK FURNITURE', 'cds music dvds'], dtype=object)

In [50]:
# achando a quantidade 
qntidade_total = len(products["product category"].unique()
)
print(qntidade_total)

74

In [35]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [67]:
# Na tabela orders, no campo 'order_status', qual destas opçoes NÃO está nesta coluna?
print(orders["order_status"].unique())

['delivered' 'invoiced' 'shipped' 'processing' 'unavailable' 'canceled'
 'created' 'approved']